CREATE TABLE authors (
id BIGINT IDENTITY PRIMARY KEY,
firstname VARCHAR(255),
lastname VARCHAR(255),
patronymic VARCHAR(255)
);

CREATE TABLE genres (
id BIGINT IDENTITY PRIMARY KEY,
name VARCHAR(255)
);

CREATE TABLE books (
id BIGINT IDENTITY PRIMARY KEY,
city VARCHAR(255),
publisher VARCHAR(255),
title VARCHAR(255),
year INTEGER
);

CREATE TABLE GENRE_BOOK (
genre_id BIGINT,
book_id BIGINT
);

CREATE TABLE AUTHOR_BOOK (
author_id BIGINT,
book_id BIGINT
);


