insert into authors (firstname, lastname, patronymic) values ('Conrade', 'Eriksson', 'Coggeshall');
insert into authors (firstname, lastname, patronymic) values ('Lelia', 'Whawell', 'Petras');
insert into authors (firstname, lastname, patronymic) values ('Andriana', 'Mapis', 'Comettoi');
insert into authors (firstname, lastname, patronymic) values ('Paige', 'Begwell', 'Elham');
insert into authors (firstname, lastname, patronymic) values ('Kiel', 'Colleck', 'Collingridge');
insert into authors (firstname, lastname, patronymic) values ('Ruth', 'Toquet', 'Borer');
insert into authors (firstname, lastname, patronymic) values ('Elden', 'Legan', 'Oloshin');
insert into authors (firstname, lastname, patronymic) values ('Nydia', 'Dunsford', 'Vandenhoff');
insert into authors (firstname, lastname, patronymic) values ('Jeffy', 'Nys', 'Aylott');
insert into authors (firstname, lastname, patronymic) values ('Freida', 'Toquet', 'Inskipp');
insert into authors (firstname, lastname, patronymic) values ('Rolfe', 'Standon', 'Annand');
insert into authors (firstname, lastname, patronymic) values ('Savina', 'Moehler', 'Toomey');
insert into authors (firstname, lastname, patronymic) values ('Imelda', 'Chafer', 'Tureville');
insert into authors (firstname, lastname, patronymic) values ('Morganne', 'Cary', 'Budgey');
insert into authors (firstname, lastname, patronymic) values ('Shelby', 'Alaway', 'Manuel');
insert into authors (firstname, lastname, patronymic) values ('Mia', 'Forsey', 'Deamer');
insert into authors (firstname, lastname, patronymic) values ('Jacky', 'Bold', 'Briiginshaw');
insert into authors (firstname, lastname, patronymic) values ('Puff', 'Keslake', 'Cancelier');
insert into authors (firstname, lastname, patronymic) values ('Dorian', 'Hurburt', 'Penvarden');
insert into authors (firstname, lastname, patronymic) values ('Shepard', 'Phipard-Shears', 'Arsmith');
insert into authors (firstname, lastname, patronymic) values ('Bink', 'Brettor', 'Scirman');
insert into authors (firstname, lastname, patronymic) values ('Barbra', 'Beggs', 'Cluet');
insert into authors (firstname, lastname, patronymic) values ('Benedick', 'Sneath', 'Morais');
insert into authors (firstname, lastname, patronymic) values ('Deanna', 'Durtnall', 'Brandon');
insert into authors (firstname, lastname, patronymic) values ('Zelda', 'Brotherheed', 'Hulson');
insert into authors (firstname, lastname, patronymic) values ('Brooks', 'Duplock', 'Heimes');
insert into authors (firstname, lastname, patronymic) values ('Sauncho', 'Clemmow', 'Hirth');
insert into authors (firstname, lastname, patronymic) values ('Ianthe', 'Driussi', 'Shee');
insert into authors (firstname, lastname, patronymic) values ('Gretna', 'McTiernan', 'Feldon');
insert into authors (firstname, lastname, patronymic) values ('Kaitlynn', 'Maffei', 'Chanter');
insert into authors (firstname, lastname, patronymic) values ('Letitia', 'McRitchie', 'Switland');
insert into authors (firstname, lastname, patronymic) values ('Gray', 'Cornell', 'Taggerty');
insert into authors (firstname, lastname, patronymic) values ('Gracie', 'Veighey', 'Spores');
insert into authors (firstname, lastname, patronymic) values ('Doralynn', 'Alesin', 'Dafforne');
insert into authors (firstname, lastname, patronymic) values ('Stacy', 'Screeton', 'Grassick');
insert into authors (firstname, lastname, patronymic) values ('Marnia', 'Botwright', 'Ridpath');
insert into authors (firstname, lastname, patronymic) values ('Abdul', 'Kaminski', 'Chesney');
insert into authors (firstname, lastname, patronymic) values ('Dunn', 'Dunbobbin', 'Dyshart');
insert into authors (firstname, lastname, patronymic) values ('Parke', 'Byrcher', 'Malloy');
insert into authors (firstname, lastname, patronymic) values ('Salim', 'Ubsdale', 'Pascall');
insert into authors (firstname, lastname, patronymic) values ('Dee', 'Abramamov', 'Najara');
insert into authors (firstname, lastname, patronymic) values ('Darya', 'Tremethack', 'Marler');
insert into authors (firstname, lastname, patronymic) values ('Angelico', 'Dugood', 'Sowrey');
insert into authors (firstname, lastname, patronymic) values ('Annabelle', 'Vergine', 'Knowles');
insert into authors (firstname, lastname, patronymic) values ('Huberto', 'Arnould', 'Barkley');
insert into authors (firstname, lastname, patronymic) values ('Aryn', 'Preshous', 'Blower');
insert into authors (firstname, lastname, patronymic) values ('Guenna', 'Feake', 'Zettoi');
insert into authors (firstname, lastname, patronymic) values ('Delmar', 'Balma', 'Swindall');
insert into authors (firstname, lastname, patronymic) values ('Bastian', 'Miners', 'Millhouse');
insert into authors (firstname, lastname, patronymic) values ('Carl', 'Greiser', 'Craighill');
insert into authors (firstname, lastname, patronymic) values ('Alley', 'Labrom', 'Shambroke');
insert into authors (firstname, lastname, patronymic) values ('Langsdon', 'Buxsey', 'Calafato');
insert into authors (firstname, lastname, patronymic) values ('Nalani', 'Kirstein', 'Kensy');
insert into authors (firstname, lastname, patronymic) values ('Linnea', 'Kienlein', 'Sawart');
insert into authors (firstname, lastname, patronymic) values ('Rickie', 'Lippitt', 'Mangenet');
insert into authors (firstname, lastname, patronymic) values ('Dulcinea', 'Roja', 'de Copeman');
insert into authors (firstname, lastname, patronymic) values ('Kiah', 'Vaughton', 'Todaro');
insert into authors (firstname, lastname, patronymic) values ('Zelig', 'Robbins', 'Kieran');
insert into authors (firstname, lastname, patronymic) values ('Bobina', 'Fernandes', 'Stuffins');
insert into authors (firstname, lastname, patronymic) values ('Murdock', 'Philippart', 'Hunday');
insert into authors (firstname, lastname, patronymic) values ('Alic', 'Devenish', 'MacNeilly');
insert into authors (firstname, lastname, patronymic) values ('Elmore', 'Vodden', 'Surgey');
insert into authors (firstname, lastname, patronymic) values ('Rikki', 'Heggadon', 'Tyzack');
insert into authors (firstname, lastname, patronymic) values ('Mickie', 'Simionescu', 'Kantor');
insert into authors (firstname, lastname, patronymic) values ('Mommy', 'Shrigley', 'Sollars');
insert into authors (firstname, lastname, patronymic) values ('Millie', 'Taillard', 'Rainsbury');
insert into authors (firstname, lastname, patronymic) values ('Constancia', 'Cicconetti', 'Verryan');
insert into authors (firstname, lastname, patronymic) values ('Sasha', 'Lampert', 'Glacken');
insert into authors (firstname, lastname, patronymic) values ('Jacob', 'Gorsse', 'Stollwerck');
insert into authors (firstname, lastname, patronymic) values ('Jolie', 'Dishmon', 'Dunckley');
insert into authors (firstname, lastname, patronymic) values ('Renado', 'Maddison', 'Kirman');
insert into authors (firstname, lastname, patronymic) values ('Arvin', 'Craig', 'Royl');
insert into authors (firstname, lastname, patronymic) values ('Ilyssa', 'Faers', 'McAlpin');
insert into authors (firstname, lastname, patronymic) values ('Zak', 'Feechan', 'Brahmer');
insert into authors (firstname, lastname, patronymic) values ('Danyette', 'Moulson', 'Boater');
insert into authors (firstname, lastname, patronymic) values ('Nelson', 'Hayball', 'Bucham');
insert into authors (firstname, lastname, patronymic) values ('Brigitte', 'Davidovits', 'Reace');
insert into authors (firstname, lastname, patronymic) values ('Winona', 'Lambird', 'Fritche');
insert into authors (firstname, lastname, patronymic) values ('Neddie', 'Alldre', 'Threadgill');
insert into authors (firstname, lastname, patronymic) values ('Stevena', 'Hebbes', 'Shoppee');
insert into authors (firstname, lastname, patronymic) values ('Corrinne', 'Mehaffey', 'Owbrick');
insert into authors (firstname, lastname, patronymic) values ('Currey', 'Walrond', 'Panner');
insert into authors (firstname, lastname, patronymic) values ('Hayden', 'Grain', 'Berick');
insert into authors (firstname, lastname, patronymic) values ('Gilda', 'Lodemann', 'Dykas');
insert into authors (firstname, lastname, patronymic) values ('Clo', 'Deneve', 'Rowter');
insert into authors (firstname, lastname, patronymic) values ('Court', 'Biffen', 'Jozefowicz');
insert into authors (firstname, lastname, patronymic) values ('Valenka', 'Devericks', 'Cluitt');
insert into authors (firstname, lastname, patronymic) values ('Kerry', 'Riddles', 'Abisetti');
insert into authors (firstname, lastname, patronymic) values ('Timmie', 'Stegel', 'Alliott');
insert into authors (firstname, lastname, patronymic) values ('Amaleta', 'Guilbert', 'Moscon');
insert into authors (firstname, lastname, patronymic) values ('Theodoric', 'Crole', 'Waggatt');
insert into authors (firstname, lastname, patronymic) values ('Ashbey', 'Anger', 'Axup');
insert into authors (firstname, lastname, patronymic) values ('Addia', 'Ridgeway', 'Marshall');
insert into authors (firstname, lastname, patronymic) values ('Melania', 'Pascall', 'Hallstone');
insert into authors (firstname, lastname, patronymic) values ('Rockwell', 'Guy', 'Feaveer');
insert into authors (firstname, lastname, patronymic) values ('Buckie', 'Derges', 'Portwain');
insert into authors (firstname, lastname, patronymic) values ('Christos', 'Espina', 'Antoszczyk');
insert into authors (firstname, lastname, patronymic) values ('Buckie', 'Rollason', 'Yarker');
insert into authors (firstname, lastname, patronymic) values ('Ebba', 'Milbourn', 'Hamman');
insert into authors (firstname, lastname, patronymic) values ('Mickie', 'Murkitt', 'Chetham');

insert into genres (name) values ('Drama');
insert into genres (name) values ('Action|Horror|Sci-Fi');
insert into genres (name) values ('Action|Adventure|Fantasy');
insert into genres (name) values ('Drama|Fantasy|Sci-Fi');
insert into genres (name) values ('Animation|Comedy|Drama');
insert into genres (name) values ('Drama');
insert into genres (name) values ('Comedy|War');
insert into genres (name) values ('Documentary');
insert into genres (name) values ('(no genres listed)');
insert into genres (name) values ('Documentary');
insert into genres (name) values ('Comedy|Horror');
insert into genres (name) values ('Documentary');
insert into genres (name) values ('Action|Animation|Drama');
insert into genres (name) values ('(no genres listed)');
insert into genres (name) values ('Adventure|Drama');
insert into genres (name) values ('Comedy|Drama|Romance');
insert into genres (name) values ('Drama|Horror|Thriller');
insert into genres (name) values ('Drama|Mystery');
insert into genres (name) values ('Documentary');
insert into genres (name) values ('Fantasy');
insert into genres (name) values ('Comedy|Romance');
insert into genres (name) values ('Adventure|Animation|Children|Comedy');
insert into genres (name) values ('Drama|IMAX');
insert into genres (name) values ('Drama');
insert into genres (name) values ('Action|Comedy');
insert into genres (name) values ('Action|Drama');
insert into genres (name) values ('Crime|Drama|Thriller');
insert into genres (name) values ('Comedy|Documentary');
insert into genres (name) values ('Drama|War');
insert into genres (name) values ('Horror|Sci-Fi|Thriller');
insert into genres (name) values ('Documentary');
insert into genres (name) values ('Drama|Sci-Fi');
insert into genres (name) values ('Comedy');
insert into genres (name) values ('Drama');
insert into genres (name) values ('Comedy');
insert into genres (name) values ('Comedy');
insert into genres (name) values ('Comedy|Drama');
insert into genres (name) values ('Comedy');
insert into genres (name) values ('Adventure|Drama|Romance');
insert into genres (name) values ('Drama');
insert into genres (name) values ('Drama|Thriller|War');
insert into genres (name) values ('Drama|Horror|Thriller');
insert into genres (name) values ('Comedy|Drama|Romance');
insert into genres (name) values ('Sci-Fi');
insert into genres (name) values ('Comedy|Horror');
insert into genres (name) values ('Action|Comedy|Drama');
insert into genres (name) values ('Comedy|Crime|Romance');
insert into genres (name) values ('Adventure|Drama|Western');
insert into genres (name) values ('Documentary|War');
insert into genres (name) values ('Drama');
insert into genres (name) values ('Comedy|Horror|Mystery|Thriller');
insert into genres (name) values ('Crime|Drama');
insert into genres (name) values ('Horror');
insert into genres (name) values ('Adventure|Drama|Thriller|War');
insert into genres (name) values ('Action|Adventure|War');
insert into genres (name) values ('Comedy|Drama|Romance');
insert into genres (name) values ('Drama');
insert into genres (name) values ('Drama');
insert into genres (name) values ('Drama|Romance');
insert into genres (name) values ('Drama');
insert into genres (name) values ('Comedy');
insert into genres (name) values ('Drama');
insert into genres (name) values ('Crime|Drama');
insert into genres (name) values ('Drama|Romance');
insert into genres (name) values ('Drama');
insert into genres (name) values ('Comedy|Drama');
insert into genres (name) values ('Drama');
insert into genres (name) values ('Children|Drama');
insert into genres (name) values ('Comedy|Romance');
insert into genres (name) values ('Drama|Romance');
insert into genres (name) values ('Comedy');
insert into genres (name) values ('Drama|Film-Noir|Thriller');
insert into genres (name) values ('Action|Crime|Drama');
insert into genres (name) values ('Romance');
insert into genres (name) values ('Horror|Thriller');
insert into genres (name) values ('Drama|Thriller');
insert into genres (name) values ('Drama');
insert into genres (name) values ('Action|Animation|Fantasy');
insert into genres (name) values ('Action|Adventure|Drama');
insert into genres (name) values ('Comedy');
insert into genres (name) values ('Documentary');
insert into genres (name) values ('Action|Animation|Drama');
insert into genres (name) values ('Drama|Romance');
insert into genres (name) values ('Drama|Film-Noir|Thriller');
insert into genres (name) values ('Drama|Musical|Romance');
insert into genres (name) values ('Crime|Drama|Film-Noir');
insert into genres (name) values ('Comedy');
insert into genres (name) values ('Action|Comedy|Crime');
insert into genres (name) values ('Action|Thriller');
insert into genres (name) values ('Drama');
insert into genres (name) values ('Documentary');
insert into genres (name) values ('Children|Comedy|Fantasy');
insert into genres (name) values ('Drama');
insert into genres (name) values ('Adventure|Animation|Children|Musical');
insert into genres (name) values ('Horror');
insert into genres (name) values ('Sci-Fi');
insert into genres (name) values ('Drama');
insert into genres (name) values ('Adventure');
insert into genres (name) values ('Comedy|Drama');
insert into genres (name) values ('Comedy|Drama');

insert into books (city, publisher, title, year) values ('Yedun', 'O’Reilly', 'No Time For Sergeants', 2002);
insert into books (city, publisher, title, year) values ('San Miguel', 'Москва', '''Salem''s Lot', 1998);
insert into books (city, publisher, title, year) values ('Cibeureum', 'Санкт-Петербург', 'Hercules and the Lost Kingdom', 2007);
insert into books (city, publisher, title, year) values ('Alcoutim', 'Москва', 'Terrorizers, The (Kong bu fen zi)', 2006);
insert into books (city, publisher, title, year) values ('Cukanguncal', 'O’Reilly', 'Rambo (Rambo 4)', 2006);
insert into books (city, publisher, title, year) values ('Sangba', 'Москва', 'Construction, The (En construcción)', 1998);
insert into books (city, publisher, title, year) values ('Mutoko', 'Москва', 'Four Minutes (Vier Minuten)', 1999);
insert into books (city, publisher, title, year) values ('Dipayal', 'Москва', 'Detective, The (C+ jing taam)', 2009);
insert into books (city, publisher, title, year) values ('Karlstad', 'Санкт-Петербург', 'Westbound', 2009);
insert into books (city, publisher, title, year) values ('Shuangxi', 'Москва', 'Bell Boy, The', 1992);
insert into books (city, publisher, title, year) values ('Sedlice', 'O’Reilly', 'Wild Horse, Wild Ride', 2004);
insert into books (city, publisher, title, year) values ('Wangfu', 'Москва', '976-EVIL II', 1994);
insert into books (city, publisher, title, year) values ('Mizhirah', 'O’Reilly', 'Black Tights (1-2-3-4 ou Les Collants noirs)', 2006);
insert into books (city, publisher, title, year) values ('Zaoshi', 'Санкт-Петербург', 'Questo piccolo grande amore', 2008);
insert into books (city, publisher, title, year) values ('Fāraskūr', 'Санкт-Петербург', 'Kedma', 1986);
insert into books (city, publisher, title, year) values ('Tanshi', 'Санкт-Петербург', 'All Cheerleaders Die', 2011);
insert into books (city, publisher, title, year) values ('Xitan', 'Санкт-Петербург', 'Wanda Sykes: Sick and Tired', 2004);
insert into books (city, publisher, title, year) values ('Pahonjean', 'O’Reilly', 'Red Balloon, The (Ballon rouge, Le)', 1986);
insert into books (city, publisher, title, year) values ('Haikou', 'Санкт-Петербург', 'Mystery Science Theater 3000: The Movie', 1999);
insert into books (city, publisher, title, year) values ('Dom Pedrito', 'Москва', 'Meet the Applegates', 1994);
insert into books (city, publisher, title, year) values ('Pasirhaur', 'Санкт-Петербург', 'Sam Peckinpah''s West: Legacy of a Hollywood Renegade', 2003);
insert into books (city, publisher, title, year) values ('Akashi', 'O’Reilly', 'Hellraiser: Inferno', 1997);
insert into books (city, publisher, title, year) values ('Sokołów Podlaski', 'O’Reilly', 'I''m Not Scared (Io non ho paura)', 2006);
insert into books (city, publisher, title, year) values ('Sladna', 'Москва', 'Lesson Plan ', 2011);
insert into books (city, publisher, title, year) values ('Francisco I Madero', 'Москва', 'Elektra Luxx', 2007);
insert into books (city, publisher, title, year) values ('Los Angeles', 'O’Reilly', 'The Amazing Dr. Clitterhouse', 2012);
insert into books (city, publisher, title, year) values ('Wiri', 'O’Reilly', 'Watership Down', 2002);
insert into books (city, publisher, title, year) values ('Oak Bay', 'Санкт-Петербург', 'Irene, Go Home! (Irena do domu!)', 2000);
insert into books (city, publisher, title, year) values ('Aracaju', 'Санкт-Петербург', 'Rockers', 2005);
insert into books (city, publisher, title, year) values ('Sainte-Anne-de-Bellevue', 'Санкт-Петербург', 'Stars in Shorts', 1985);
insert into books (city, publisher, title, year) values ('Jönköping', 'Санкт-Петербург', 'Cinderella Liberty', 2003);
insert into books (city, publisher, title, year) values ('Prozor', 'O’Reilly', 'Paint It Yellow (Rang De Basanti)', 2008);
insert into books (city, publisher, title, year) values ('Bauchi', 'Москва', 'Dream a Little Dream', 1997);
insert into books (city, publisher, title, year) values ('Montaigu', 'Санкт-Петербург', 'Wallace & Gromit: A Close Shave', 1996);
insert into books (city, publisher, title, year) values ('Aihua', 'O’Reilly', 'Vie meilleure, Une (Better Life, A)', 2010);
insert into books (city, publisher, title, year) values ('Imbituva', 'O’Reilly', 'Centurion', 2009);
insert into books (city, publisher, title, year) values ('Nariño', 'O’Reilly', 'The Mark of Cain', 2000);
insert into books (city, publisher, title, year) values ('Utara', 'O’Reilly', 'Tenderness', 2011);
insert into books (city, publisher, title, year) values ('Tiebukenwusan', 'O’Reilly', 'Transporter 3', 1998);
insert into books (city, publisher, title, year) values ('Marondera', 'Санкт-Петербург', 'Scorpio', 1988);
insert into books (city, publisher, title, year) values ('El Aguacate', 'Москва', 'Peter and Vandy', 2010);
insert into books (city, publisher, title, year) values ('Miaotang', 'O’Reilly', 'The Horribly Slow Murderer with the Extremely Inefficient Weapon', 2005);
insert into books (city, publisher, title, year) values ('Liancheng', 'Санкт-Петербург', 'Chasers, The (Jakten)', 1989);
insert into books (city, publisher, title, year) values ('Zhouhe', 'Москва', 'Boys on the Side', 1995);
insert into books (city, publisher, title, year) values ('Arnaía', 'O’Reilly', 'Strange One, The', 2007);
insert into books (city, publisher, title, year) values ('Gaoling', 'O’Reilly', 'Funny About Love', 1986);
insert into books (city, publisher, title, year) values ('Jeziora Wielkie', 'Санкт-Петербург', 'Who Killed Nancy?', 2010);
insert into books (city, publisher, title, year) values ('Jablanovec', 'Москва', 'What A Man', 2005);
insert into books (city, publisher, title, year) values ('Niechanowo', 'Санкт-Петербург', 'Garfield''s Halloween Adventure', 1995);
insert into books (city, publisher, title, year) values ('Borok', 'O’Reilly', 'Animal House', 1996);
insert into books (city, publisher, title, year) values ('Maizuru', 'O’Reilly', 'Young and the Dead, The', 1998);
insert into books (city, publisher, title, year) values ('Lũng Hồ', 'Санкт-Петербург', 'Perfect Sisters', 2000);
insert into books (city, publisher, title, year) values ('Ta‘izz', 'Москва', 'Halloween II', 2012);
insert into books (city, publisher, title, year) values ('Laugar', 'Санкт-Петербург', 'Core, The', 2011);
insert into books (city, publisher, title, year) values ('Selaawi', 'O’Reilly', 'Body Shots', 2005);
insert into books (city, publisher, title, year) values ('Jibiya', 'Санкт-Петербург', 'Moebius', 1997);
insert into books (city, publisher, title, year) values ('Leninskoye', 'Санкт-Петербург', 'Reds', 2007);
insert into books (city, publisher, title, year) values ('Lindavista', 'Москва', 'After Earth', 2003);
insert into books (city, publisher, title, year) values ('Mungyeong', 'Санкт-Петербург', 'Monsieur Vincent', 1986);
insert into books (city, publisher, title, year) values ('Lourdes', 'Санкт-Петербург', 'George Lopez: It''s Not Me, It''s You', 2010);
insert into books (city, publisher, title, year) values ('Çobansığnaq', 'Санкт-Петербург', 'Il cappotto di legno', 2012);
insert into books (city, publisher, title, year) values ('Pruszcz', 'Москва', 'Clean and Sober', 1990);
insert into books (city, publisher, title, year) values ('Borucin', 'O’Reilly', 'I Are You, You Am Me (Tenkosei)', 2007);
insert into books (city, publisher, title, year) values ('Sittwe', 'O’Reilly', 'Born to Race', 2009);
insert into books (city, publisher, title, year) values ('Usogorsk', 'O’Reilly', 'Miss Sweden (Fröken Sverige)', 2004);
insert into books (city, publisher, title, year) values ('Nizhniy Kislyay', 'Санкт-Петербург', 'Fawlty Towers (1975-1979)', 1985);
insert into books (city, publisher, title, year) values ('Galveias', 'Санкт-Петербург', 'Three Stooges Meet Hercules, The', 1996);
insert into books (city, publisher, title, year) values ('Jincang', 'Санкт-Петербург', 'Did You Hear About the Morgans?', 1993);
insert into books (city, publisher, title, year) values ('Jangkungkusumo', 'O’Reilly', 'At Any Price', 2009);
insert into books (city, publisher, title, year) values ('Jieshou', 'O’Reilly', 'Bronies: The Extremely Unexpected Adult Fans of My Little Pony', 2002);
insert into books (city, publisher, title, year) values ('Pung-Pang', 'Санкт-Петербург', 'The Heavy', 1996);
insert into books (city, publisher, title, year) values ('Amieirinha', 'Санкт-Петербург', '100 Years of Evil', 1995);
insert into books (city, publisher, title, year) values ('Ladhewāla Warāich', 'Санкт-Петербург', 'Someone''s Watching Me!', 1996);
insert into books (city, publisher, title, year) values ('Thị Trấn Thọ Xuân', 'O’Reilly', 'Long Way Round', 2000);
insert into books (city, publisher, title, year) values ('San Miguel', 'Москва', 'Funny Lady', 2007);
insert into books (city, publisher, title, year) values ('Nabari', 'Санкт-Петербург', 'Frankenstein', 2011);
insert into books (city, publisher, title, year) values ('Kyjov', 'O’Reilly', 'Escape to Witch Mountain', 1984);
insert into books (city, publisher, title, year) values ('Irapa', 'Москва', 'Bye-Bye Bin Laden', 1999);
insert into books (city, publisher, title, year) values ('San Antonio de los Baños', 'O’Reilly', 'Jerry Springer: The Opera', 2005);
insert into books (city, publisher, title, year) values ('San Alberto', 'Санкт-Петербург', 'They Bite', 2011);
insert into books (city, publisher, title, year) values ('Botevgrad', 'Москва', 'Road to Bali', 2002);
insert into books (city, publisher, title, year) values ('Luján', 'O’Reilly', 'Soul Plane', 2006);
insert into books (city, publisher, title, year) values ('Huangascar', 'Санкт-Петербург', 'Black White + Gray: A Portrait of Sam Wagstaff and Robert Mapplethorpe ', 2011);
insert into books (city, publisher, title, year) values ('Chrząstowice', 'O’Reilly', 'Paraíso Travel', 2009);
insert into books (city, publisher, title, year) values ('Xincheng Chengguanzhen', 'Санкт-Петербург', 'Human Traffic', 1985);
insert into books (city, publisher, title, year) values ('Capim Grosso', 'Санкт-Петербург', 'Tom Sawyer', 2012);
insert into books (city, publisher, title, year) values ('Hamberang Sabrang', 'Санкт-Петербург', 'Force of One, A', 2006);
insert into books (city, publisher, title, year) values ('Sabadell', 'O’Reilly', 'Santa Clause 3: The Escape Clause, The', 2008);
insert into books (city, publisher, title, year) values ('Mariscala', 'Санкт-Петербург', 'Galileo', 2009);
insert into books (city, publisher, title, year) values ('Synya', 'Москва', 'César', 1993);
insert into books (city, publisher, title, year) values ('Xinxian', 'Санкт-Петербург', 'Saving General Yang', 2010);
insert into books (city, publisher, title, year) values ('Lampa', 'O’Reilly', 'Amen.', 2005);
insert into books (city, publisher, title, year) values ('Léfka', 'O’Reilly', 'Queen of Hearts', 2006);
insert into books (city, publisher, title, year) values ('Quibal', 'O’Reilly', 'Topsy-Turvy', 2007);
insert into books (city, publisher, title, year) values ('Velké Hoštice', 'Санкт-Петербург', 'The Big Shave', 1998);
insert into books (city, publisher, title, year) values ('Podujeva', 'Санкт-Петербург', 'Three Resurrected Drunkards (Kaette kita yopparai)', 2001);
insert into books (city, publisher, title, year) values ('Fort Worth', 'Санкт-Петербург', 'Major Movie Star', 2010);
insert into books (city, publisher, title, year) values ('Thākurgaon', 'O’Reilly', 'Justin and the Knights of Valour', 1992);
insert into books (city, publisher, title, year) values ('Kiviõli', 'Москва', 'Borrowed Time', 1990);
insert into books (city, publisher, title, year) values ('Aranđelovac', 'Москва', 'The Disappeared', 1999);

insert into GENRE_BOOK (genre_id, book_id) values (62, 1);
insert into GENRE_BOOK (genre_id, book_id) values (39, 2);
insert into GENRE_BOOK (genre_id, book_id) values (35, 3);
insert into GENRE_BOOK (genre_id, book_id) values (19, 4);
insert into GENRE_BOOK (genre_id, book_id) values (84, 5);
insert into GENRE_BOOK (genre_id, book_id) values (26, 6);
insert into GENRE_BOOK (genre_id, book_id) values (96, 7);
insert into GENRE_BOOK (genre_id, book_id) values (54, 8);
insert into GENRE_BOOK (genre_id, book_id) values (9, 9);
insert into GENRE_BOOK (genre_id, book_id) values (62, 10);
insert into GENRE_BOOK (genre_id, book_id) values (17, 11);
insert into GENRE_BOOK (genre_id, book_id) values (56, 12);
insert into GENRE_BOOK (genre_id, book_id) values (43, 13);
insert into GENRE_BOOK (genre_id, book_id) values (28, 14);
insert into GENRE_BOOK (genre_id, book_id) values (41, 15);
insert into GENRE_BOOK (genre_id, book_id) values (10, 16);
insert into GENRE_BOOK (genre_id, book_id) values (35, 17);
insert into GENRE_BOOK (genre_id, book_id) values (6, 18);
insert into GENRE_BOOK (genre_id, book_id) values (37, 19);
insert into GENRE_BOOK (genre_id, book_id) values (55, 20);
insert into GENRE_BOOK (genre_id, book_id) values (15, 21);
insert into GENRE_BOOK (genre_id, book_id) values (15, 22);
insert into GENRE_BOOK (genre_id, book_id) values (90, 23);
insert into GENRE_BOOK (genre_id, book_id) values (46, 24);
insert into GENRE_BOOK (genre_id, book_id) values (73, 25);
insert into GENRE_BOOK (genre_id, book_id) values (58, 26);
insert into GENRE_BOOK (genre_id, book_id) values (1, 27);
insert into GENRE_BOOK (genre_id, book_id) values (87, 28);
insert into GENRE_BOOK (genre_id, book_id) values (99, 29);
insert into GENRE_BOOK (genre_id, book_id) values (89, 30);
insert into GENRE_BOOK (genre_id, book_id) values (53, 31);
insert into GENRE_BOOK (genre_id, book_id) values (50, 32);
insert into GENRE_BOOK (genre_id, book_id) values (79, 33);
insert into GENRE_BOOK (genre_id, book_id) values (55, 34);
insert into GENRE_BOOK (genre_id, book_id) values (55, 35);
insert into GENRE_BOOK (genre_id, book_id) values (10, 36);
insert into GENRE_BOOK (genre_id, book_id) values (9, 37);
insert into GENRE_BOOK (genre_id, book_id) values (34, 38);
insert into GENRE_BOOK (genre_id, book_id) values (20, 39);
insert into GENRE_BOOK (genre_id, book_id) values (97, 40);
insert into GENRE_BOOK (genre_id, book_id) values (87, 41);
insert into GENRE_BOOK (genre_id, book_id) values (23, 42);
insert into GENRE_BOOK (genre_id, book_id) values (70, 43);
insert into GENRE_BOOK (genre_id, book_id) values (99, 44);
insert into GENRE_BOOK (genre_id, book_id) values (35, 45);
insert into GENRE_BOOK (genre_id, book_id) values (83, 46);
insert into GENRE_BOOK (genre_id, book_id) values (4, 47);
insert into GENRE_BOOK (genre_id, book_id) values (50, 48);
insert into GENRE_BOOK (genre_id, book_id) values (57, 49);
insert into GENRE_BOOK (genre_id, book_id) values (30, 50);
insert into GENRE_BOOK (genre_id, book_id) values (33, 51);
insert into GENRE_BOOK (genre_id, book_id) values (89, 52);
insert into GENRE_BOOK (genre_id, book_id) values (23, 53);
insert into GENRE_BOOK (genre_id, book_id) values (84, 54);
insert into GENRE_BOOK (genre_id, book_id) values (56, 55);
insert into GENRE_BOOK (genre_id, book_id) values (45, 56);
insert into GENRE_BOOK (genre_id, book_id) values (77, 57);
insert into GENRE_BOOK (genre_id, book_id) values (63, 58);
insert into GENRE_BOOK (genre_id, book_id) values (73, 59);
insert into GENRE_BOOK (genre_id, book_id) values (85, 60);
insert into GENRE_BOOK (genre_id, book_id) values (39, 61);
insert into GENRE_BOOK (genre_id, book_id) values (32, 62);
insert into GENRE_BOOK (genre_id, book_id) values (52, 63);
insert into GENRE_BOOK (genre_id, book_id) values (79, 64);
insert into GENRE_BOOK (genre_id, book_id) values (100, 65);
insert into GENRE_BOOK (genre_id, book_id) values (32, 66);
insert into GENRE_BOOK (genre_id, book_id) values (20, 67);
insert into GENRE_BOOK (genre_id, book_id) values (77, 68);
insert into GENRE_BOOK (genre_id, book_id) values (65, 69);
insert into GENRE_BOOK (genre_id, book_id) values (39, 70);
insert into GENRE_BOOK (genre_id, book_id) values (19, 71);
insert into GENRE_BOOK (genre_id, book_id) values (23, 72);
insert into GENRE_BOOK (genre_id, book_id) values (40, 73);
insert into GENRE_BOOK (genre_id, book_id) values (52, 74);
insert into GENRE_BOOK (genre_id, book_id) values (18, 75);
insert into GENRE_BOOK (genre_id, book_id) values (20, 76);
insert into GENRE_BOOK (genre_id, book_id) values (6, 77);
insert into GENRE_BOOK (genre_id, book_id) values (54, 78);
insert into GENRE_BOOK (genre_id, book_id) values (21, 79);
insert into GENRE_BOOK (genre_id, book_id) values (99, 80);
insert into GENRE_BOOK (genre_id, book_id) values (55, 81);
insert into GENRE_BOOK (genre_id, book_id) values (4, 82);
insert into GENRE_BOOK (genre_id, book_id) values (95, 83);
insert into GENRE_BOOK (genre_id, book_id) values (10, 84);
insert into GENRE_BOOK (genre_id, book_id) values (30, 85);
insert into GENRE_BOOK (genre_id, book_id) values (69, 86);
insert into GENRE_BOOK (genre_id, book_id) values (77, 87);
insert into GENRE_BOOK (genre_id, book_id) values (10, 88);
insert into GENRE_BOOK (genre_id, book_id) values (56, 89);
insert into GENRE_BOOK (genre_id, book_id) values (49, 90);
insert into GENRE_BOOK (genre_id, book_id) values (45, 91);
insert into GENRE_BOOK (genre_id, book_id) values (47, 92);
insert into GENRE_BOOK (genre_id, book_id) values (25, 93);
insert into GENRE_BOOK (genre_id, book_id) values (76, 94);
insert into GENRE_BOOK (genre_id, book_id) values (1, 95);
insert into GENRE_BOOK (genre_id, book_id) values (83, 96);
insert into GENRE_BOOK (genre_id, book_id) values (30, 97);
insert into GENRE_BOOK (genre_id, book_id) values (50, 98);
insert into GENRE_BOOK (genre_id, book_id) values (51, 99);
insert into GENRE_BOOK (genre_id, book_id) values (9, 100);

insert into AUTHOR_BOOK (author_id, book_id) values (13, 1);
insert into AUTHOR_BOOK (author_id, book_id) values (10, 2);
insert into AUTHOR_BOOK (author_id, book_id) values (16, 3);
insert into AUTHOR_BOOK (author_id, book_id) values (68, 4);
insert into AUTHOR_BOOK (author_id, book_id) values (7, 5);
insert into AUTHOR_BOOK (author_id, book_id) values (50, 6);
insert into AUTHOR_BOOK (author_id, book_id) values (17, 7);
insert into AUTHOR_BOOK (author_id, book_id) values (6, 8);
insert into AUTHOR_BOOK (author_id, book_id) values (73, 9);
insert into AUTHOR_BOOK (author_id, book_id) values (99, 10);
insert into AUTHOR_BOOK (author_id, book_id) values (27, 11);
insert into AUTHOR_BOOK (author_id, book_id) values (41, 12);
insert into AUTHOR_BOOK (author_id, book_id) values (94, 13);
insert into AUTHOR_BOOK (author_id, book_id) values (35, 14);
insert into AUTHOR_BOOK (author_id, book_id) values (37, 15);
insert into AUTHOR_BOOK (author_id, book_id) values (37, 16);
insert into AUTHOR_BOOK (author_id, book_id) values (98, 17);
insert into AUTHOR_BOOK (author_id, book_id) values (61, 18);
insert into AUTHOR_BOOK (author_id, book_id) values (93, 19);
insert into AUTHOR_BOOK (author_id, book_id) values (92, 20);
insert into AUTHOR_BOOK (author_id, book_id) values (58, 21);
insert into AUTHOR_BOOK (author_id, book_id) values (99, 22);
insert into AUTHOR_BOOK (author_id, book_id) values (73, 23);
insert into AUTHOR_BOOK (author_id, book_id) values (93, 24);
insert into AUTHOR_BOOK (author_id, book_id) values (91, 25);
insert into AUTHOR_BOOK (author_id, book_id) values (52, 26);
insert into AUTHOR_BOOK (author_id, book_id) values (50, 27);
insert into AUTHOR_BOOK (author_id, book_id) values (22, 28);
insert into AUTHOR_BOOK (author_id, book_id) values (79, 29);
insert into AUTHOR_BOOK (author_id, book_id) values (89, 30);
insert into AUTHOR_BOOK (author_id, book_id) values (52, 31);
insert into AUTHOR_BOOK (author_id, book_id) values (46, 32);
insert into AUTHOR_BOOK (author_id, book_id) values (45, 33);
insert into AUTHOR_BOOK (author_id, book_id) values (42, 34);
insert into AUTHOR_BOOK (author_id, book_id) values (84, 35);
insert into AUTHOR_BOOK (author_id, book_id) values (27, 36);
insert into AUTHOR_BOOK (author_id, book_id) values (66, 37);
insert into AUTHOR_BOOK (author_id, book_id) values (15, 38);
insert into AUTHOR_BOOK (author_id, book_id) values (7, 39);
insert into AUTHOR_BOOK (author_id, book_id) values (96, 40);
insert into AUTHOR_BOOK (author_id, book_id) values (69, 41);
insert into AUTHOR_BOOK (author_id, book_id) values (49, 42);
insert into AUTHOR_BOOK (author_id, book_id) values (96, 43);
insert into AUTHOR_BOOK (author_id, book_id) values (58, 44);
insert into AUTHOR_BOOK (author_id, book_id) values (33, 45);
insert into AUTHOR_BOOK (author_id, book_id) values (23, 46);
insert into AUTHOR_BOOK (author_id, book_id) values (36, 47);
insert into AUTHOR_BOOK (author_id, book_id) values (14, 48);
insert into AUTHOR_BOOK (author_id, book_id) values (83, 49);
insert into AUTHOR_BOOK (author_id, book_id) values (52, 50);
insert into AUTHOR_BOOK (author_id, book_id) values (75, 51);
insert into AUTHOR_BOOK (author_id, book_id) values (11, 52);
insert into AUTHOR_BOOK (author_id, book_id) values (90, 53);
insert into AUTHOR_BOOK (author_id, book_id) values (75, 54);
insert into AUTHOR_BOOK (author_id, book_id) values (67, 55);
insert into AUTHOR_BOOK (author_id, book_id) values (93, 56);
insert into AUTHOR_BOOK (author_id, book_id) values (22, 57);
insert into AUTHOR_BOOK (author_id, book_id) values (54, 58);
insert into AUTHOR_BOOK (author_id, book_id) values (7, 59);
insert into AUTHOR_BOOK (author_id, book_id) values (76, 60);
insert into AUTHOR_BOOK (author_id, book_id) values (56, 61);
insert into AUTHOR_BOOK (author_id, book_id) values (29, 62);
insert into AUTHOR_BOOK (author_id, book_id) values (66, 63);
insert into AUTHOR_BOOK (author_id, book_id) values (48, 64);
insert into AUTHOR_BOOK (author_id, book_id) values (34, 65);
insert into AUTHOR_BOOK (author_id, book_id) values (77, 66);
insert into AUTHOR_BOOK (author_id, book_id) values (46, 67);
insert into AUTHOR_BOOK (author_id, book_id) values (41, 68);
insert into AUTHOR_BOOK (author_id, book_id) values (73, 69);
insert into AUTHOR_BOOK (author_id, book_id) values (76, 70);
insert into AUTHOR_BOOK (author_id, book_id) values (69, 71);
insert into AUTHOR_BOOK (author_id, book_id) values (13, 72);
insert into AUTHOR_BOOK (author_id, book_id) values (21, 73);
insert into AUTHOR_BOOK (author_id, book_id) values (21, 74);
insert into AUTHOR_BOOK (author_id, book_id) values (95, 75);
insert into AUTHOR_BOOK (author_id, book_id) values (16, 76);
insert into AUTHOR_BOOK (author_id, book_id) values (98, 77);
insert into AUTHOR_BOOK (author_id, book_id) values (56, 78);
insert into AUTHOR_BOOK (author_id, book_id) values (100, 79);
insert into AUTHOR_BOOK (author_id, book_id) values (18, 80);
insert into AUTHOR_BOOK (author_id, book_id) values (89, 81);
insert into AUTHOR_BOOK (author_id, book_id) values (15, 82);
insert into AUTHOR_BOOK (author_id, book_id) values (39, 83);
insert into AUTHOR_BOOK (author_id, book_id) values (58, 84);
insert into AUTHOR_BOOK (author_id, book_id) values (36, 85);
insert into AUTHOR_BOOK (author_id, book_id) values (91, 86);
insert into AUTHOR_BOOK (author_id, book_id) values (99, 87);
insert into AUTHOR_BOOK (author_id, book_id) values (66, 88);
insert into AUTHOR_BOOK (author_id, book_id) values (32, 89);
insert into AUTHOR_BOOK (author_id, book_id) values (30, 90);
insert into AUTHOR_BOOK (author_id, book_id) values (11, 91);
insert into AUTHOR_BOOK (author_id, book_id) values (31, 92);
insert into AUTHOR_BOOK (author_id, book_id) values (97, 93);
insert into AUTHOR_BOOK (author_id, book_id) values (4, 94);
insert into AUTHOR_BOOK (author_id, book_id) values (84, 95);
insert into AUTHOR_BOOK (author_id, book_id) values (73, 96);
insert into AUTHOR_BOOK (author_id, book_id) values (79, 97);
insert into AUTHOR_BOOK (author_id, book_id) values (74, 98);
insert into AUTHOR_BOOK (author_id, book_id) values (98, 99);
insert into AUTHOR_BOOK (author_id, book_id) values (19, 100);
